build:
	rustc shim.rs -C panic=abort --crate-type=staticlib --target armv7a-none-eabi --emit obj
	arm-none-eabi-ld -T shim.ld -o shim shim.o
	arm-none-eabi-objcopy -O binary -j .text -j .jump_table shim shim.bin

disassemble: build
	arm-none-eabi-objdump -d shim

inspect: build
	arm-none-eabi-objdump -x shim

clean:
	rm -f shim shim.o shim.bin