[package]
name = "vex-v5-qemu-host"
version = "0.1.0"
edition = "2021"

[dependencies]
vex-v5-qemu-protocol = { path = "../protocol" }
tokio = { version = "1.39.3", features = ["full"] }
miette = "7.2.0"
thiserror = "1.0.63"
bincode = "2.0.0-rc.3"
cobs = "0.2.3"
log = "0.4.22"
