[package]
name = "vex-v5-qemu-protocol"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Host-to-guest serial communications layer for vex-v5-qemu."
authors = [
    "vexide",
    "doinkythederp <doinkythederp@icloud.com>",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "Tropical",
]

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex-sdk = "0.19.0"
bitflags = "2.6.0"
serde = { version = "1.0", default-features = false, features = [
    "derive",
], optional = true }
kurbo = { version = "0.11.3", default-features = false, features = ["libm"] }
derive_more = { version = "2.0.1", features = ["from"], default-features = false }
color = { version = "0.3.1", default-features = false, features = ["libm"]}

[features]
serde = ["dep:serde", "kurbo/serde", "color/serde"]
