[package]
name = "vex-v5-qemu-protocol"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Host-to-guest serial communications layer for vex-v5-qemu."
authors = [
    "vexide",
    "doinkythederp <doinkythederp@icloud.com>",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "Tropical",
]

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex-sdk = "0.19.0"
bincode = { version = "2.0.0-rc.3", default-features = false, features = [
    "derive",
    "alloc",
] }
bitflags = "2.6.0"
serde = { version = "1.0", default-features = false, features = [
    "derive",
], optional = true }

[features]
serde = ["dep:serde"]
