[package]
name = "vex-v5-qemu-host"
version = "0.1.0"
edition = "2021"
authors = [
    "vexide",
    "doinkythederp <doinkythederp@icloud.com>",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "Tropical",
]

[lints]
workspace = true

[dependencies]
vex-v5-qemu-protocol = { path = "../protocol" }
tokio = { version = "1.39.3", features = ["full"] }
miette = "7.2.0"
thiserror = "1.0.63"
bincode = "2.0.0-rc.3"
cobs = "0.2.3"
log = "0.4.22"
image = { version = "0.25.2", default-features = false }
vex-v5-display-simulator = { version = "0.1.0", path = "../display" }
bytemuck = "1.17.0"
