[package]
name = "client"
publish = false # Must be published as a Tauri app
version = "0.1.0"
description = "A Tauri App"
authors = [
    "vexide",
    "doinkythederp <doinkythederp@icloud.com>",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "Tropical",
]
license = "MIT"
repository = "https://github.com/vexide/vex-v5-qemu"
edition = "2021"
rust-version = "1.70"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc.2", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc.2", features = [] }
tauri-plugin-shell = "2.0.0-beta.0"
tauri-plugin-log = { version = "2.0.0-beta.0", features = ["colored"] }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

tokio = { version = "1.39.2", features = ["full"] }

vex-v5-qemu-protocol = { path = "../../protocol", features = ["serde"] }
vex-v5-qemu-host = { path = "../../host" }
vex-v5-display-simulator = { version = "0.1.0", path = "../../display" }
bincode = "2.0.0-rc.3"
log = "0.4.22"
time = { version = "0.3.36", features = ["formatting"] }
tauri-plugin-dialog = "2.0.0-beta.0"
bytemuck = "1.17.0"
image = { version = "0.25.2", default-features = false }
